name: build.yml
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        assertions:
          - phpunit
          - webmozart
          - beberlei
          - ouzo
          - phpunit-comparator
          - zenstruck
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          ini-file: 'development'
          coverage: none

      - run: composer install

      - run: vendor/bin/behat
        env:
          BEHAT_ASSERTION_LIBRARY: ${{ matrix.assertions }}
